### ISSUE TITLE
Babel and Webpackcompatibility issue

### ISSUE THREAD

**Issue by JolomiTee** [speer-technologies/aircall#22]
I have compatibility issues coming from my node version throwing errors against the webpack and babel packages or plugins. I'm not too sure. But can I start a repo from scratch using a build tool like Vivo? while still maintaining most of the codebase content except the babel and webpack config files?

**Comment by saurav-prasad** [comment]
> I have compatibility issues coming from my node version throwing errors against the webpack and babel packages or plugins. I'm not too sure. But can I start a repo from scratch using a build tool like Vivo? while still maintaining most of the codebase content except the babel and webpack config files?

Even I am facing the same problem
